<?php

namespace Database\Seeders;
use Illuminate\Database\Seeder;
use App\Models\County;

class CountySeeder extends Seeder
{
   public function run()
   {
      County::factory()->create(['id'=>1, 'title'=>'Bedfordshire', 'country_id'=>1, 'active'=>1]);
      County::factory()->create(['id'=>2, 'title'=>'Berkshire', 'country_id'=>1, 'active'=>1]);
      County::factory()->create(['id'=>3, 'title'=>'Bristol', 'country_id'=>1, 'active'=>1]);
      County::factory()->create(['id'=>4, 'title'=>'Buckinghamshire', 'country_id'=>1, 'active'=>1]);
      County::factory()->create(['id'=>5, 'title'=>'Cambridgeshire', 'country_id'=>1, 'active'=>1]);
      County::factory()->create(['id'=>6, 'title'=>'Cheshire', 'country_id'=>1, 'active'=>1]);
      County::factory()->create(['id'=>7, 'title'=>'Cornwall', 'country_id'=>1, 'active'=>1]);
      County::factory()->create(['id'=>8, 'title'=>'Cumbria', 'country_id'=>1, 'active'=>1]);
      County::factory()->create(['id'=>9, 'title'=>'Derbyshire', 'country_id'=>1, 'active'=>1]);
      County::factory()->create(['id'=>10, 'title'=>'Devon', 'country_id'=>1, 'active'=>1]);
      County::factory()->create(['id'=>11, 'title'=>'Dorset', 'country_id'=>1, 'active'=>1]);
      County::factory()->create(['id'=>12, 'title'=>'Durham', 'country_id'=>1, 'active'=>1]);
      County::factory()->create(['id'=>13, 'title'=>'East Riding of Yorkshire', 'country_id'=>1, 'active'=>1]);
      County::factory()->create(['id'=>14, 'title'=>'East Sussex', 'country_id'=>1, 'active'=>1]);
      County::factory()->create(['id'=>15, 'title'=>'Essex', 'country_id'=>1, 'active'=>1]);
      County::factory()->create(['id'=>16, 'title'=>'Gloucestershire', 'country_id'=>1, 'active'=>1]);
      County::factory()->create(['id'=>17, 'title'=>'Greater London', 'country_id'=>1, 'active'=>1]);
      County::factory()->create(['id'=>18, 'title'=>'Greater Manchester', 'country_id'=>1, 'active'=>1]);
      County::factory()->create(['id'=>19, 'title'=>'Hampshire', 'country_id'=>1, 'active'=>1]);
      County::factory()->create(['id'=>20, 'title'=>'Herefordshire', 'country_id'=>1, 'active'=>1]);
      County::factory()->create(['id'=>21, 'title'=>'Hertfordshire', 'country_id'=>1, 'active'=>1]);
      County::factory()->create(['id'=>22, 'title'=>'Isle of Wight', 'country_id'=>1, 'active'=>1]);
      County::factory()->create(['id'=>23, 'title'=>'Kent', 'country_id'=>1, 'active'=>1]);
      County::factory()->create(['id'=>24, 'title'=>'Lancashire', 'country_id'=>1, 'active'=>1]);
      County::factory()->create(['id'=>25, 'title'=>'Leicestershire', 'country_id'=>1, 'active'=>1]);
      County::factory()->create(['id'=>26, 'title'=>'Lincolnshire', 'country_id'=>1, 'active'=>1]);
      County::factory()->create(['id'=>27, 'title'=>'Merseyside', 'country_id'=>1, 'active'=>1]);
      County::factory()->create(['id'=>28, 'title'=>'Norfolk', 'country_id'=>1, 'active'=>1]);
      County::factory()->create(['id'=>29, 'title'=>'Northamptonshire', 'country_id'=>1, 'active'=>1]);
      County::factory()->create(['id'=>30, 'title'=>'Northumberland', 'country_id'=>1, 'active'=>1]);
      County::factory()->create(['id'=>31, 'title'=>'North Yorkshire', 'country_id'=>1, 'active'=>1]);
      County::factory()->create(['id'=>32, 'title'=>'Nottinghamshire', 'country_id'=>1, 'active'=>1]);
      County::factory()->create(['id'=>33, 'title'=>'Oxfordshire', 'country_id'=>1, 'active'=>1]);
      County::factory()->create(['id'=>34, 'title'=>'Rutland', 'country_id'=>1, 'active'=>1]);
      County::factory()->create(['id'=>35, 'title'=>'Shropshire', 'country_id'=>1, 'active'=>1]);
      County::factory()->create(['id'=>36, 'title'=>'Somerset', 'country_id'=>1, 'active'=>1]);
      County::factory()->create(['id'=>37, 'title'=>'South Yorkshire', 'country_id'=>1, 'active'=>1]);
      County::factory()->create(['id'=>38, 'title'=>'Staffordshire', 'country_id'=>1, 'active'=>1]);
      County::factory()->create(['id'=>39, 'title'=>'Suffolk', 'country_id'=>1, 'active'=>1]);
      County::factory()->create(['id'=>40, 'title'=>'Surrey', 'country_id'=>1, 'active'=>1]);
      County::factory()->create(['id'=>41, 'title'=>'Tyne and Wear', 'country_id'=>1, 'active'=>1]);
      County::factory()->create(['id'=>42, 'title'=>'Warwickshire', 'country_id'=>1, 'active'=>1]);
      County::factory()->create(['id'=>43, 'title'=>'West Midlands', 'country_id'=>1, 'active'=>1]);
      County::factory()->create(['id'=>44, 'title'=>'West Sussex', 'country_id'=>1, 'active'=>1]);
      County::factory()->create(['id'=>45, 'title'=>'West Yorkshire', 'country_id'=>1, 'active'=>1]);
      County::factory()->create(['id'=>46, 'title'=>'Wiltshire', 'country_id'=>1, 'active'=>1]);
      County::factory()->create(['id'=>47, 'title'=>'Worcestershire', 'country_id'=>1, 'active'=>1]);
      County::factory()->create(['id'=>48, 'title'=>'Antrim', 'country_id'=>2, 'active'=>1]);
      County::factory()->create(['id'=>49, 'title'=>'Armagh', 'country_id'=>2, 'active'=>1]);
      County::factory()->create(['id'=>50, 'title'=>'Down', 'country_id'=>2, 'active'=>1]);
      County::factory()->create(['id'=>51, 'title'=>'Fermangh', 'country_id'=>2, 'active'=>1]);
      County::factory()->create(['id'=>52, 'title'=>'Londonderry', 'country_id'=>2, 'active'=>1]);
      County::factory()->create(['id'=>53, 'title'=>'Tyrone', 'country_id'=>2, 'active'=>1]);
      County::factory()->create(['id'=>54, 'title'=>'Aberdeenshire', 'country_id'=>3, 'active'=>1]);
      County::factory()->create(['id'=>55, 'title'=>'Angus', 'country_id'=>3, 'active'=>1]);
      County::factory()->create(['id'=>56, 'title'=>'Argyll and Bute', 'country_id'=>3, 'active'=>1]);
      County::factory()->create(['id'=>57, 'title'=>'City of Aberdeen', 'country_id'=>3, 'active'=>1]);
      County::factory()->create(['id'=>58, 'title'=>'City of Dundee', 'country_id'=>3, 'active'=>1]);
      County::factory()->create(['id'=>59, 'title'=>'City of Edinburgh', 'country_id'=>3, 'active'=>1]);
      County::factory()->create(['id'=>60, 'title'=>'City of Glasgow', 'country_id'=>3, 'active'=>1]);
      County::factory()->create(['id'=>61, 'title'=>'Clackmannanshire', 'country_id'=>3, 'active'=>1]);
      County::factory()->create(['id'=>62, 'title'=>'Dumfries & Galloway', 'country_id'=>3, 'active'=>1]);
      County::factory()->create(['id'=>63, 'title'=>'East Ayrshire', 'country_id'=>3, 'active'=>1]);
      County::factory()->create(['id'=>64, 'title'=>'East Dunbartonshire', 'country_id'=>3, 'active'=>1]);
      County::factory()->create(['id'=>65, 'title'=>'East Lothian', 'country_id'=>3, 'active'=>1]);
      County::factory()->create(['id'=>66, 'title'=>'East Renfrewshire', 'country_id'=>3, 'active'=>1]);     
      County::factory()->create(['id'=>67, 'title'=>'Falkirk', 'country_id'=>3, 'active'=>1]);
      County::factory()->create(['id'=>68, 'title'=>'Fife', 'country_id'=>3, 'active'=>1]);
      County::factory()->create(['id'=>69, 'title'=>'Highland', 'country_id'=>3, 'active'=>1]);
      County::factory()->create(['id'=>70, 'title'=>'Inverclyde', 'country_id'=>3, 'active'=>1]);
      County::factory()->create(['id'=>71, 'title'=>'Midlothian', 'country_id'=>3, 'active'=>1]);
      County::factory()->create(['id'=>72, 'title'=>'Moray', 'country_id'=>3, 'active'=>1]);
      County::factory()->create(['id'=>73, 'title'=>'North Ayrshire', 'country_id'=>3, 'active'=>1]);
      County::factory()->create(['id'=>74, 'title'=>'North Lanarkshire', 'country_id'=>3, 'active'=>1]);
      County::factory()->create(['id'=>75, 'title'=>'Orkney', 'country_id'=>3, 'active'=>1]);
      County::factory()->create(['id'=>76, 'title'=>'Perth and Kinross', 'country_id'=>3, 'active'=>1]);
      County::factory()->create(['id'=>77, 'title'=>'Renfrewshire', 'country_id'=>3, 'active'=>1]);
      County::factory()->create(['id'=>78, 'title'=>'Scottish Borders', 'country_id'=>3, 'active'=>1]);
      County::factory()->create(['id'=>79, 'title'=>'Shetland', 'country_id'=>3, 'active'=>1]);
      County::factory()->create(['id'=>80, 'title'=>'South Ayrshire', 'country_id'=>3, 'active'=>1]);
      County::factory()->create(['id'=>81, 'title'=>'South Lanarkshire', 'country_id'=>3, 'active'=>1]);
      County::factory()->create(['id'=>82, 'title'=>'Stirling', 'country_id'=>3, 'active'=>1]);
      County::factory()->create(['id'=>83, 'title'=>'West Dunbartonshire', 'country_id'=>3, 'active'=>1]);
      County::factory()->create(['id'=>84, 'title'=>'Western Isles', 'country_id'=>3, 'active'=>1]);
      County::factory()->create(['id'=>85, 'title'=>'West Lothian', 'country_id'=>3, 'active'=>1]);
      County::factory()->create(['id'=>86, 'title'=>'Anglesey', 'country_id'=>4, 'active'=>1]);
      County::factory()->create(['id'=>87, 'title'=>'Blaenau Gwent', 'country_id'=>4, 'active'=>1]);
      County::factory()->create(['id'=>88, 'title'=>'Bridgend', 'country_id'=>4, 'active'=>1]);
      County::factory()->create(['id'=>89, 'title'=>'Caerphilly', 'country_id'=>4, 'active'=>1]);
      County::factory()->create(['id'=>90, 'title'=>'Cardiff', 'country_id'=>4, 'active'=>1]);
      County::factory()->create(['id'=>91, 'title'=>'Carmarthenshire', 'country_id'=>4, 'active'=>1]);
      County::factory()->create(['id'=>92, 'title'=>'Ceredigion', 'country_id'=>4, 'active'=>1]);
      County::factory()->create(['id'=>93, 'title'=>'Conwy', 'country_id'=>4, 'active'=>1]);
      County::factory()->create(['id'=>94, 'title'=>'Denbighshire', 'country_id'=>4, 'active'=>1]);
      County::factory()->create(['id'=>95, 'title'=>'Flintshire', 'country_id'=>4, 'active'=>1]);
      County::factory()->create(['id'=>96, 'title'=>'Gwynedd', 'country_id'=>4, 'active'=>1]);
      County::factory()->create(['id'=>97, 'title'=>'Merthyr Tydfil', 'country_id'=>4, 'active'=>1]);
      County::factory()->create(['id'=>98, 'title'=>'Monmouthshire', 'country_id'=>4, 'active'=>1]);
      County::factory()->create(['id'=>99, 'title'=>'Neath Port Talbot', 'country_id'=>4, 'active'=>1]);
      County::factory()->create(['id'=>100, 'title'=>'Newport', 'country_id'=>4, 'active'=>1]);
      County::factory()->create(['id'=>101, 'title'=>'Pembrokeshire', 'country_id'=>4, 'active'=>1]);
      County::factory()->create(['id'=>102, 'title'=>'Powys', 'country_id'=>4, 'active'=>1]);
      County::factory()->create(['id'=>103, 'title'=>'Rhondda, Cynon, Taff', 'country_id'=>4, 'active'=>1]);
      County::factory()->create(['id'=>104, 'title'=>'Swansea', 'country_id'=>4, 'active'=>1]);
      County::factory()->create(['id'=>105, 'title'=>'Torfaen', 'country_id'=>4, 'active'=>1]);
      County::factory()->create(['id'=>106, 'title'=>'Vale of Glamorgan', 'country_id'=>4, 'active'=>1]);
      County::factory()->create(['id'=>107, 'title'=>'Wrexham', 'country_id'=>4, 'active'=>1]);
   }
}