<?php

namespace Database\Seeders;
use Illuminate\Database\Seeder;
use App\Models\County;

class CountySeeder extends Seeder
{
   public function run()
   {
      County::factory()->create(['id'=>2, 'title'=>'Bedfordshire', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>3, 'title'=>'Berkshire', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>4, 'title'=>'Buckinghamshire', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>5, 'title'=>'Cambridgeshire', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>7, 'title'=>'Cheshire', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>10, 'title'=>'Cornwall', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>11, 'title'=>'Cumbria', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>12, 'title'=>'Derbyshire', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>13, 'title'=>'Devon', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>14, 'title'=>'Dorset', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>18, 'title'=>'East Sussex', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>19, 'title'=>'Essex', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>20, 'title'=>'Fife', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>21, 'title'=>'Gloucestershire', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>23, 'title'=>'Greater London', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>24, 'title'=>'Greater Manchester', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>27, 'title'=>'Gwynedd', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>28, 'title'=>'Hampshire', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>29, 'title'=>'Herefordshire', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>30, 'title'=>'Hertfordshire', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>31, 'title'=>'Highland', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>34, 'title'=>'Isle of Wight', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>36, 'title'=>'Kent', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>37, 'title'=>'Lancashire', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>38, 'title'=>'Leicestershire', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>39, 'title'=>'Lincolnshire', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>41, 'title'=>'Merseyside', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>43, 'title'=>'Norfolk', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>44, 'title'=>'North Yorkshire', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>45, 'title'=>'Northamptonshire', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>46, 'title'=>'Northumberland', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>47, 'title'=>'Nottinghamshire', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>49, 'title'=>'Oxfordshire', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>50, 'title'=>'Powys', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>52, 'title'=>'Shetland', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>53, 'title'=>'Shropshire', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>54, 'title'=>'Somerset', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>56, 'title'=>'South Yorkshire', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>57, 'title'=>'Staffordshire', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>59, 'title'=>'Suffolk', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>60, 'title'=>'Surrey', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>63, 'title'=>'Warwickshire', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>65, 'title'=>'West Midlands', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>66, 'title'=>'West Sussex', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>67, 'title'=>'West Yorkshire', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>68, 'title'=>'Western Isles', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>69, 'title'=>'Wiltshire', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>70, 'title'=>'Worcestershire', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>73, 'title'=>'Aberdeenshire', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>74, 'title'=>'Ceredigion', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>75, 'title'=>'Angus', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>76, 'title'=>'Antrim', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>77, 'title'=>'Argyll & Bute', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>78, 'title'=>'Armagh', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>79, 'title'=>'Ayrshire', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>80, 'title'=>'Banffshire', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>81, 'title'=>'Bath and North East Somerset', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>82, 'title'=>'Berwickshire', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>83, 'title'=>'Blaenau Gwent', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>84, 'title'=>'Borders', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>85, 'title'=>'Bridgend', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>86, 'title'=>'Bristol', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>87, 'title'=>'Caerphilly', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>88, 'title'=>'Caithness', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>89, 'title'=>'Cardiff', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>90, 'title'=>'Carmarthenshire', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>91, 'title'=>'Clackmannanshire', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>92, 'title'=>'Conwy', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>93, 'title'=>'County Durham', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>94, 'title'=>'Denbighshire', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>95, 'title'=>'Down', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>96, 'title'=>'Dumfries & Galloway', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>97, 'title'=>'Dunbartonshire', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>98, 'title'=>'East Ayrshire', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>99, 'title'=>'East Dunbartonshire', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>100, 'title'=>'East Lothian', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>101, 'title'=>'East Renfrewshire', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>102, 'title'=>'East Riding of Yorkshire', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>103, 'title'=>'Fermanagh', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>104, 'title'=>'Flintshire', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>105, 'title'=>'Inverclyde', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>106, 'title'=>'Isle of Anglesey', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>107, 'title'=>'Isles of Scilly', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>108, 'title'=>'Kincardineshire', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>109, 'title'=>'Lanarkshire', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>110, 'title'=>'Londonderry', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>111, 'title'=>'Merthyr Tydfil', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>112, 'title'=>'Midlothian', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>113, 'title'=>'Monmouthshire', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>114, 'title'=>'Moray', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>115, 'title'=>'Neath Port Talbot.', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>116, 'title'=>'Newport.', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>117, 'title'=>'North Ayrshire', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>118, 'title'=>'North Lanarkshire', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>119, 'title'=>'North Somerset', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>120, 'title'=>'Orkney', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>121, 'title'=>'Pembrokeshire', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>122, 'title'=>'Perth & Kinross', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>123, 'title'=>'Renfrewshire', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>124, 'title'=>'Republic of Ireland (all)', 'country_id'=>232, 'active'=>1]);      
      County::factory()->create(['id'=>125, 'title'=>'Rhondda Cynon Taff', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>126, 'title'=>'Rutland', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>127, 'title'=>'South Ayrshire', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>128, 'title'=>'South Gloucestershire', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>129, 'title'=>'South Lanarkshire', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>130, 'title'=>'Stirlingshire', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>131, 'title'=>'Swansea', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>132, 'title'=>'Torfaen', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>133, 'title'=>'Tyne & Wear', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>134, 'title'=>'Tyrone', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>135, 'title'=>'Vale of Glamorgan', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>136, 'title'=>'West Dunbartonshire', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>137, 'title'=>'West Lothian', 'country_id'=>232, 'active'=>1]);
      County::factory()->create(['id'=>138, 'title'=>'Wrexham', 'country_id'=>232, 'active'=>1]);
   }
}